import { Nft, NftSource, NftType } from './types'

export const IPFS_GATEWAY = 'https://cloudflare-ipfs.com'

export const nftSources: NftSource = {
  [NftType.PANCAKE]: {
    address: {
      56: '0xD7286BFe8B97922F81bda4a49e959903D882eB82',
      97: '0x6314f44e15c92d9034eab24d4f83bdbf22af3f7e',
    },
    identifierKey: 'image',
  },
  [NftType.MIXIE]: {
    address: {
      56: '0xD7286BFe8B97922F81bda4a49e959903D882eB82',
      97: '0x6314f44e15c92d9034eab24d4f83bdbf22af3f7e',
    },
    identifierKey: 'image',
  },
}

const Nfts: Nft[] = [
  {
    name: 'Texas Cowboy',
    description: 'Aww, looks like eating pancakes all day is tough work. Sweet dreams!',
    images: {
      lg: 'Cute-cowboy.jpg',
      md: 'Cute-cowboy.jpg',
      sm: 'Cute-cowboy.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/Cute-cowboy.jpg',
      blur: 'Cute-cowboy.jpg',
    },
    sortOrder: 999,
    identifier: 'cowboy',
    type: NftType.PANCAKE,
    variationId: 1,
  },
  {
    name: 'Patrick Boy',
    description: 'Sunny is always cheerful when there are pancakes around. Smile!',
    images: {
      lg: 'Patrick-Boy.jpg',
      md: 'Patrick-Boy.jpg',
      sm: 'Patrick-Boy.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/Patrick-Boy.jpg',
      blur: 'Patrick-Boy',
    },
    sortOrder: 999,
    identifier: 'Patrick-Boy',
    type: NftType.PANCAKE,
    variationId: 2,
  },
  {
    name: 'Baby Boss',
    description: "Don't let that dopey smile deceive you... Churro's a master DEX chef!",
    images: {
      lg: 'baby-boss.jpg',
      md: 'baby-boss.jpg',
      sm: 'baby-boss.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/baby-boss.jpg',
      blur: 'baby-boss.jpg',
    },
    sortOrder: 999,
    identifier: 'baby-boss',
    type: NftType.PANCAKE,
    variationId: 3,
  },
  {
    name: 'Bomb!!!!!',
    description: "Nommm... Oh hi, I'm just meditating on the meaning of DEX.",
    images: {
      lg: 'bomb-cartoon.jpg',
      md: 'bomb-cartoon.jpg',
      sm: 'bomb-cartoon.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/bomb-cartoon.jpg',
      blur: 'bomb-cartoon.jpg',
    },
    sortOrder: 999,
    identifier: 'bomb',
    type: NftType.PANCAKE,
    variationId: 4,
  },
  {
    name: 'Builder',
    description: "Three guesses what's put that twinkle in those eyes! (Hint: it's DEX)",
    images: {
      lg: 'builder.jpg',
      md: 'builder.jpg',
      sm: 'builder.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/builder.jpg',
      blur: 'builder.jpg',
    },
    sortOrder: 999,
    identifier: 'builder',
    type: NftType.PANCAKE,
    variationId: 5,
  },
  {
    name: 'Businessman',
    description: 'Stories were told, and songs were sung, about Chef Mixie’s pancakes and her big Syrup gun.',
    images: {
      lg: 'businessman.jpg',
      md: 'businessman.jpg',
      sm: 'businessman.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/businessman.jpg',
    },
    sortOrder: 999,
    identifier: 'businessman',
    type: NftType.MIXIE,
    variationId: 6,
  },
  {
    name: 'Sealing Chocolate',
    description: '',
    images: {
      lg: 'chocolate.jpg',
      md: 'chocolate.jpg',
      sm: 'chocolate.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/chocolate.jpg',
    },
    sortOrder: 999,
    identifier: 'chocolate',
    type: NftType.MIXIE,
    variationId: 7,
  },
  {
    name: 'Leprechaun',
    description: 'Stories were told, and songs were sung, about Chef Mixie’s pancakes and her big Syrup gun.',
    images: {
      lg: 'leprechaun.jpg',
      md: 'leprechaun.jpg',
      sm: 'leprechaun.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/leprechaun.jpg',
    },
    sortOrder: 999,
    identifier: 'leprechaun',
    type: NftType.MIXIE,
    variationId: 8,
  },
  {
    name: 'Happy Girl',
    description: 'Eggscellent! Celebrating Syrup Storm winning the Easter Battle!',
    images: {
      lg: 'madam.jpg',
      md: 'madam.jpg',
      sm: 'madam.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/madam.jpg',
    },
    sortOrder: 999,
    identifier: 'madam',
    type: NftType.PANCAKE,
    variationId: 9,
  },
  {
    name: "Cool Panda",
    description: 'Melting Easter eggs and melting hearts!',
    images: {
      lg: 'panda.jpg',
      md: 'panda.jpg',
      sm: 'panda.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/panda.jpg',
    },
    sortOrder: 999,
    identifier: 'panda',
    type: NftType.PANCAKE,
    variationId: 10,
  },
  // {
  //   name: "Cute Pig",
  //   description: 'Watch out for Flipsie’s spatula smash!',
  //   images: {
  //     lg: 'pig-gif-tbox.jpg',
  //     md: 'pig-gif-tbox.jpg',
  //     sm: 'pig-gif-tbox.jpg',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/pig-gif.jpg',
  //   },
  //   sortOrder: 999,
  //   identifier: 'piggift',
  //   type: NftType.PANCAKE,
  //   variationId: 11,
  // },
  {
    name: "Police",
    description: 'Do you like chocolate with your syrup? Go long!',
    images: {
      lg: 'police-coin.jpg',
      md: 'police-coin.jpg',
      sm: 'police-coin.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/police-coin.jpg',
    },
    sortOrder: 999,
    identifier: 'police',
    type: NftType.PANCAKE,
    variationId: 12,
  },
  {
    name: 'Rich Donkey',
    description: 'Happy Niu Year! This bunny’s excited for the year of the bull (market!)',
    images: {
      lg: 'rich-donkey.jpg',
      md: 'rich-donkey.jpg',
      sm: 'rich-donkey.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/rich-donkey.jpg',
    },
    sortOrder: 999,
    identifier: 'donkey',
    type: NftType.PANCAKE,
    variationId: 13,
  },
  {
    name: 'Rich Mouse',
    description: "Oopsie daisy! Hiccup's had a bit of an accident. Poor little fella.",
    images: {
      lg: 'rich-mouse.jpg',
      md: 'rich-mouse.jpg',
      sm: 'rich-mouse.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/rich-mouse.jpg',
    },
    sortOrder: 999,
    identifier: 'rich-mouse',
    type: NftType.PANCAKE,
    variationId: 14,
  },
  {
    name: 'Rich Pig',
    description: 'These bunnies love nothing more than swapping pancakes. Especially on BSC.',
    images: {
      lg: 'rich-pig.jpg',
      md: 'rich-pig.jpg',
      sm: 'rich-pig.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/rich-pig.jpg',
      blur: 'rich-pig.jpg',
    },
    sortOrder: 999,
    identifier: 'rich-pig',
    type: NftType.PANCAKE,
    variationId: 15,
  },
  {
    name: 'Uncle Sam',
    description: "It's raining syrup on this bunny, but he doesn't seem to mind. Can you blame him?",
    images: {
      lg: 'sam.jpg',
      md: 'sam.jpg',
      sm: 'sam.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/sam.jpg',
      blur: 'sam.jpg',
    },
    sortOrder: 999,
    identifier: 'sam',
    type: NftType.PANCAKE,
    variationId: 16,
  },
  {
    name: 'Crypto Thief',
    description: "These bunnies like their pancakes with blueberries. What's your favorite topping?",
    images: {
      lg: 'thief.jpg',
      md: 'thief.jpg',
      sm: 'thief.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/thief.jpg',
      blur: 'thief.jpg',
    },
    sortOrder: 999,
    identifier: 'thief',
    type: NftType.PANCAKE,
    variationId: 17,
  },
  {
    name: 'Sealing Wax',
    description: "Love makes the world go 'round... but so do pancakes. And these bunnies know it.",
    images: {
      lg: 'wax.jpg',
      md: 'wax.jpg',
      sm: 'wax.jpg',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmP4Mc2osdvSR8HaAUTyrpC7rheru3fEPNewGtfVCeBdXE/wax.jpg',
      blur: 'wax.jpg',
    },
    sortOrder: 999,
    identifier: 'wax',
    type: NftType.PANCAKE,
    variationId: 18,
  },
]

export default Nfts
